// Generated by scripts/import_and_optimize_projects.py
import projectsJson from './projectsData.json';

export const ALL_PROJECTS = projectsJson.projects;
export const HOMEPAGE_HIGHLIGHTS = projectsJson.homepage;

export const CATEGORIES = [
  { id: 'all', label: 'All Projects' },
  { id: 'residential', label: 'Residential' },
  { id: 'commercial', label: 'Commercial' },
  { id: 'hospitality', label: 'Hospitality' },
  { id: 'show-flats', label: 'Show Flats & 3D' },
];

export function getAllProjects() {
  return ALL_PROJECTS;
}

export function getProjectBySlug(slug) {
  return ALL_PROJECTS.find((p) => p.slug === slug) || null;
}

export function getFeaturedProjects() {
  // Selected high-impact showcase projects for homepage
  const featuredSlugs = [
    'haldiram-hospitality',
    'ghatkopar-penthouse',
    'powai-residence',
    'jkt-corporate-office',
    'bhayander-residence',
    'matunga-residence'
  ];
  return ALL_PROJECTS.filter((p) => featuredSlugs.includes(p.slug));
}
